AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SMS OTP Authentication System - Lambda Functions Only

Parameters:
  TwilioAccountSid:
    Type: String
    Description: Twilio Account SID
    Default: AC6510cade2d7d758b5f6a2d7902bd89e3

  TwilioAuthToken:
    Type: String
    Description: Twilio Auth Token
    NoEcho: true
    Default: a9916d8ef46d887d347b72cdec88d29a

  TwilioPhoneNumber:
    Type: String
    Description: Twilio Phone Number
    Default: +15855801246

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DEBUG_LOGGING: "true"
        SESSIONS_TABLE: sms-otp-sessions
        RECORDS_TABLE: sms-otp-records
        RATE_LIMITS_TABLE: sms-otp-rate-limits
        AUDIT_LOGS_TABLE: sms-otp-audit-logs
        SMS_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/sms-otp-sms-delivery"
        EVENTS_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/sms-otp-events"
        TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
        TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
        TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber

Resources:
  ValidateQRFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: validate-qr
      CodeUri: dist/validateQR
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Events:
        ValidateQR:
          Type: HttpApi
          Properties:
            Path: /validate-qr
            Method: post
            ApiId: !Ref HttpApi

  RequestOTPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: request-otp
      CodeUri: dist/requestOTP
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Events:
        RequestOTP:
          Type: HttpApi
          Properties:
            Path: /request-otp
            Method: post
            ApiId: !Ref HttpApi

  VerifyOTPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: verify-otp
      CodeUri: dist/verifyOTP
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Events:
        VerifyOTP:
          Type: HttpApi
          Properties:
            Path: /verify-otp
            Method: post
            ApiId: !Ref HttpApi

  SMSSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sms-sender
      CodeUri: dist/smsSender
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:sms-otp-sms-delivery"
            BatchSize: 10

  TwilioWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: twilio-webhook
      CodeUri: dist/twilioWebhook
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Events:
        TwilioWebhook:
          Type: HttpApi
          Properties:
            Path: /twilio-webhook
            Method: post
            ApiId: !Ref HttpApi

  # 🆕 NEW: Get OTP Function (for demo/testing purposes)
  GetOTPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-otp
      CodeUri: dist/getOTP
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Description: Retrieves actual OTP for demo/testing (requires DEBUG_LOGGING=true)
      Events:
        GetOTP:
          Type: HttpApi
          Properties:
            Path: /get-otp
            Method: get
            ApiId: !Ref HttpApi

  # 🆕 NEW: Check Eligibility Function (discount/offer API)
  CheckEligibilityFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: check-eligibility
      CodeUri: dist/checkEligibility
      Handler: app.lambdaHandler
      Role: arn:aws:iam::082800993317:role/sms-otp-lambda-execution-role
      Description: Checks discount eligibility and sends SMS offer via Twilio
      Events:
        CheckEligibility:
          Type: HttpApi
          Properties:
            Path: /check-eligibility
            Method: post
            ApiId: !Ref HttpApi

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        MaxAge: 300
        AllowCredentials: false

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  ValidateQRUrl:
    Description: Validate QR endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/validate-qr"

  RequestOTPUrl:
    Description: Request OTP endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/request-otp"

  VerifyOTPUrl:
    Description: Verify OTP endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/verify-otp"

  TwilioWebhookUrl:
    Description: Twilio Webhook URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/twilio-webhook"

  # 🆕 NEW OUTPUTS
  GetOTPUrl:
    Description: Get OTP endpoint (for demo/testing)
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/get-otp"

  CheckEligibilityUrl:
    Description: Check Eligibility endpoint
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod/check-eligibility"
